version: "2"

services:
  frontend-src:
    image: frontend-src
    build: ./services/frontend
    container_name: frontend-src
    volumes:
      - ./volumes/frontend:/orakwlum


  frontend-nginx:
    restart: always
    image: nginx
    container_name: frontend-nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/frontend/www:/usr/share/nginx/html:ro
